### ISSUE TITLE
Benutzer

### ISSUE THREAD

**Issue by maxxmodding** [spaceCRAFTprojekt/SpaceCraft#20]
Wir brauchen auch noch eine Liste mit Spielern, aus der ich dann im Loginbereich auswählen kann, ob es den Spieler schon gibt und die entsprechenden Daten geladen werden sollen oder ob er neu erstellt werden soll. (Player (class) login)

**Comment by alex-unknown** [comment]
Ich versteh das Problem nicht: 
`public static Player newPlayer(String name){
        int id=((Integer) new Request(-1,"Main.newPlayer",Integer.class,name).ret).intValue(); //Kopie des Players am Server
        if (id!=-1)
            return new Player(id,name,true); //Player hier am Client
        return null;
    }`
Diese Methode macht doch genau das was du brauchst. Diese Zeile int id = ... frag den Server, ob es den Spieler schon gibt. Wenn ja, dann gibt sie dessen Id zurück, wenn nein, dann -1. Dann kannst du dir Methode ändern (die ist im Player im client), so dass es in else-Block dem Server eienen Kommand schickt, den Spieler zu erstellen.
Da musst du halt ein bisschen lesen, wie das mit den Requests geht. Als Vorlage kannst du ja gleich diesen Request `new Request(-1,"Main.newPlayer",Integer.class,name).ret).intValue(); ` verwenden. Und dann einfach mal in die Klasse Request schauen, was da eig passiert, dann im Server schauen, welche Methode da aufgerufen wird usw. Und dann nach dem Bauplan einnen neuen Request zum erstellen eines neuen Spielers schreiben. 

mug

**Comment by alex-unknown** [comment]
Und den neuen Request musst du dann auch unbedingt in der Request Liste (in client.Request) ergänzen

**Comment by alex-unknown** [comment]
Wie stehts?

**Comment by Schnux2** [comment]
Das sollte jetzt eigentlich unnötig geworden sein, oder?
