### ISSUE TITLE
Auswahl von Blöcken mit der Maus

### ISSUE THREAD

**Issue by alex-unknown** [spaceCRAFTprojekt/SpaceCraft#26]
Grund für Offset suchen/korrigieren. Bessere Methode dafür schreiben. GetBlockAtPos()
Auch im Bezug auf die Fließkommakoordinaten #24

**Comment by alex-unknown** [comment]
`public VektorD getUpperLeftCorner(VektorD pos){
        // das -0.5 ist eine hässliche Lösung von issue #26. Ich hab kleine Ahnung warum es geht aber es geht...
        return pos.add(ClientSettings.PLAYERC_FIELD_OF_VIEW.toDouble().multiply(-0.5) ).add(new VektorD(0.5,-0.5));
    }`
Ich glaub der Kommentar erklärt den aktuellen Stand sehr gut. Ich denke spätersten, wenn wir fließkommakoords haben wird sich da nochmal was ändern müssen...

**Comment by Schnux2** [comment]
Das Problem ist nicht die Mausauswahl, sondern die Darstellung mit PaintPanels, die aus irgendeinem Grund alle einen Offset haben.

**Comment by spaceCRAFTprojekt** [comment]
Problem ist wieder da

**Comment by spaceCRAFTprojekt** [comment]
`MouseEvent eLayered = SwingUtilities.convertMouseEvent(frame, e, frame.getLayeredPane());  // Übersetzt das Koosy in das Koosy eines LayeredPanes (Issue #26)`

Ich liebe Java.
