### ISSUE TITLE
Keplerbahnen

### ISSUE THREAD

**Issue by Schnux2** [spaceCRAFTprojekt/SpaceCraft#3]
"Die Strecke entlang der Keplerbahn, die für den direkten Weg-Zeit-Zusammenhang gebraucht wird, besitzt nur in Spezialfällen eine analytische Lösung". (https://de.wikipedia.org/wiki/Bahngeschwindigkeit_%28Astronomie%29)
"Die Kepler-Gleichung ist nicht in geschlossener Form nach der exzentrischen Anomalie E(t) auflösbar". (https://de.wikipedia.org/wiki/Kepler-Gleichung)
Wenn ich das richtig verstehe, dann kann man zwar die Parameter einer Keplerbahn (große Halbachse, kleine Halbachse, etc.) aus Startwerten für Ort und Geschwindigkeit berechnen, daraus aber keine Funktion entwickeln, aus der sich Ort und Geschwindigkeit in Abhängigkeit von der Zeit herauslesen lassen (außer zu speziellen Zeiten). Das macht die ganzen Keplerellipsen irgendwie sinnlos, oder? Vielleicht könnte man sie noch als Verifizierung hernehmen, aber nicht als viel mehr.
Fällt irgendjemandem etwas besseres ein?
LG

**Comment by spaceCRAFTprojekt** [comment]
Lösung nur nummerisch
