### ISSUE TITLE
2 Spieler mit gleichem Namen können sich einloggen

### ISSUE THREAD

**Issue by alex-unknown** [spaceCRAFTprojekt/SpaceCraft#31]
Der Titel sagt eig alles

**Comment by maxxmodding** [comment]
Ich schau’s mir mal heute Abend an

**Comment by spaceCRAFTprojekt** [comment]
![hc_107](https://user-images.githubusercontent.com/49288158/58356587-33199280-7e78-11e9-8104-05ee5ba7869a.png)

**Comment by Schnux2** [comment]
Jetzt nicht mehr, soweit ich weiß.
