### ISSUE TITLE
Bilder für das Wiki

### ISSUE THREAD

**Issue by maxhipp** [spaceCRAFTprojekt/SpaceCraft#37]
![startmenu](https://user-images.githubusercontent.com/34799688/59093932-5717b200-8915-11e9-968a-afdc3c8da057.PNG)

**Comment by alex-unknown** [comment]
witzig

**Comment by spaceCRAFTprojekt** [comment]
![hc_178](https://user-images.githubusercontent.com/49288158/60387314-78e20000-9aa1-11e9-9d4a-2b5a52a06048.png)
